name: Java CI with Maven

on:
  push:
    branches: ["any"]
  pull_request:
    branches: ["any"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # vou para a root

    - name: Set up JDK 17
      uses: actions/setup-java@v3 # indica aonde vou trabalhar
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with maven
      run: mvn -B package --file pom.xml

    - name: Run Tests
      run: mvn test

